// Context-specific validation. Passwords are not HTML-sanitized or silently altered.
export class ValidationError extends Error { constructor(message='Invalid input.'){super(message);this.name='ValidationError';this.status=400;} }
export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function uuid(value){if(typeof value!=='string'||!UUID.test(value))throw new ValidationError('Invalid record ID.');return value.toLowerCase();}
export function integer(value,min=1,max=2147483646){if(!Number.isSafeInteger(value)||value<min||value>max)throw new ValidationError('Invalid numeric value.');return value;}
export function object(value,allowed,required=allowed){if(!value||typeof value!=='object'||Array.isArray(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))throw new ValidationError();if(Object.keys(value).some(k=>!allowed.includes(k))||required.some(k=>!Object.hasOwn(value,k)))throw new ValidationError('Unexpected or missing fields.');return value;}
export function string(value,min,max,label='value',{trim=false,controls=false}={}){if(typeof value!=='string')throw new ValidationError(`Invalid ${label}.`);const v=trim?value.trim():value;if(v.length<min||v.length>max||(!controls&&/[\u0000-\u001f\u007f]/u.test(value)))throw new ValidationError(`Invalid ${label} length or characters.`);return v;}
export function credentials(email,password,signup=false){email=string(email,3,254,'email',{trim:true}).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(email))throw new ValidationError('Enter a valid email address.');return {email,password:string(password,signup?14:1,256,'account password',{controls:true})};}
export function website(value){value=string(value,0,2048,'website',{trim:true});if(!value)return '';let u;try{u=new URL(value);}catch{throw new ValidationError('Use a full HTTPS website address.');}if(u.protocol!=='https:'||u.username||u.password)throw new ValidationError('Use HTTPS without credentials in the address.');u.hash='';u.search='';return u.href;}
export function login(value){object(value,['name','url','username','password','notes']);return {name:string(value.name,1,100,'name',{trim:true}),url:website(value.url),username:string(value.username,1,320,'username',{trim:true}),password:string(value.password,1,2048,'password',{controls:true}),notes:string(value.notes,0,4000,'notes',{controls:true})};}
export function canonical64(value,minBytes,maxBytes){if(typeof value!=='string'||value.length>4*Math.ceil(maxBytes/3)||value.length%4||! /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw new ValidationError('Invalid encrypted data.');let bytes;try{bytes=atob(value);}catch{throw new ValidationError('Invalid encrypted data.');}if(bytes.length<minBytes||bytes.length>maxBytes||btoa(bytes)!==value)throw new ValidationError('Invalid encrypted data.');return value;}
export function envelope(value,maxBytes=32768){object(value,['v','iv','data']);if(value.v!==1)throw new ValidationError('Unsupported encrypted format.');return {v:1,iv:canonical64(value.iv,12,12),data:canonical64(value.data,16,maxBytes)};}
export function metadata(value){object(value,['salt','iterations','verifier']);if(value.iterations!==600000)throw new ValidationError('Unsupported vault key settings.');return {salt:canonical64(value.salt,32,32),iterations:600000,verifier:envelope(value.verifier,512)};}
export function metadataRow(value,uid){object(value,['user_id','salt','iterations','verifier','created_at'],['user_id','salt','iterations','verifier']);if(uuid(value.user_id)!==uuid(uid))throw new ValidationError('Account mismatch.');return {...metadata({salt:value.salt,iterations:value.iterations,verifier:value.verifier}),user_id:uid,created_at:value.created_at};}
export function itemRow(value,uid){object(value,['id','user_id','encrypted','revision','created_at','updated_at'],['id','user_id','encrypted','revision']);if(uuid(value.user_id)!==uuid(uid))throw new ValidationError('Account mismatch.');return {id:uuid(value.id),user_id:uid,encrypted:envelope(value.encrypted),revision:integer(value.revision),created_at:value.created_at,updated_at:value.updated_at};}
export function session(value){if(!value||typeof value!=='object')throw new ValidationError('Invalid session.');const uid=uuid(value.user?.id);if(value.user.is_anonymous)throw new ValidationError('An email account is required.');const access_token=string(value.access_token,10,16384,'access token'),refresh_token=string(value.refresh_token,10,4096,'refresh token');const expires_at=value.expires_at||Math.floor(Date.now()/1000)+integer(value.expires_in,1,86400);integer(expires_at,1,9999999999);return {access_token,refresh_token,expires_at,user:{id:uid,email:credentials(value.user.email,'x').email,is_anonymous:false,factors:Array.isArray(value.user.factors)?value.user.factors.filter(f=>f?.status==='verified').map(f=>({id:uuid(f.id),factor_type:f.factor_type,status:'verified'})):[]}};}
export function jwk(value){object(value,['kty','k','alg','ext','key_ops'],['kty','k']);if(value.kty!=='oct'||typeof value.k!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(value.k)||(value.alg&&value.alg!=='A256GCM'))throw new ValidationError('Invalid vault key.');return {kty:'oct',k:value.k,alg:'A256GCM',ext:true,key_ops:['encrypt','decrypt']};}
export function safeMessage(error){if(error instanceof ValidationError||error?.safe)return error.message;return 'The operation failed. Check your connection and try again.';}
